version: '3.5'

services:
  parking-control-db:
    image: postgres:9.6
    container_name: parking-control-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parking-control-db 
    ports:
      - "5432:5432"
      
  app:
     container_name: parking-control-api
     image: parking-control-api:1.0
     restart: always
     build: 
        context: .
     ports:
      - "8080:8080"
     depends_on:
       - parking-control-db
      
  portainer:
     image: portainer/portainer-ce:2.0.0
     container_name: portainer-io
     command: -H unix:///var/run/docker.sock
     restart: always
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     ports:
      - "9000:9000"

