version: '3'
services:
  app:
    image: parking-control-api:1.0
    container_name: parking-spot
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - parking-spot-db
    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:9001/parking-control-db
  parking-control-db:
    image: postgres:9.6
    restart: always
    container_name: parking-control-db
    volumes:
      - C:\Docker\PostgreSql\data:/var/lib/postgresql/data
    ports:
      - "9001:9001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking-control-db
  portainer:
    image: portainer/portainer-ce:2.11.1
    container_name: portainer-io
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"